# Dependabot configuration for automated dependency updates
# This helps maintain security by keeping dependencies up to date

version: 2
updates:
  # Frontend (Node.js) dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "rduffyuk"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Backend (Python) dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "rduffyuk"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rduffyuk"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # Docker dependencies (if any Dockerfiles present)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rduffyuk"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"